---
# tasks file for jenkins-role

  - name: upgrade all packages
    yum:
      name: '*'
      state: present
  - name: Add repository jenkins
    yum_repository:
      name: jenkins
      description: Jenkins yum repo
      baseurl: http://pkg.jenkins.io/redhat-stable
      gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
  - name: upgrade all packages
    yum:
      name: '*'
      state: present
  - name: installing java and jenkins
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - java
      - jenkins
  - name: starting jenkins
    service:
      name: jenkins
      state: started
